
data_transformer_path: scalers\data_transformer.pkl
train_data_path: data\house-pricing\train.csv
val_data_path: data\house-pricing\test.csv

data_dir: path\to\data

# ---------------
# Hyperparameters
# ---------------
epochs: 10000
batch_size: 256

vae:
  embedding_dim: 32
  compress_dims: [256, 128, 64, 32]
  decompress_dims: [32, 64, 128, 256]

  generation:
    n_samples_to_generate: 10000
    new_generated_data_filename: name_of_generated_file.csv
    model_path: path/to/model/checkpoint.ckpt

gan:
  embedding_dim: 128
  generator_dims: [256, 256, 256]
  discriminator_dims: [256, 256, 256]

  generation:
    n_samples_to_generate: 10000
    new_generated_data_filename: name_of_generated_file.csv
    model_path: path/to/model/checkpoint.ckpt
